### ISSUE TITLE
Error on input js editting

### ISSUE THREAD

**Issue by pittoch** [JuanCarniglia/kbn_picture_values_vis#1]
Hi,

When I wan to personalize the the json label, it's not possible. The label is not editing:
http://www.hostingpics.net/viewer.php?id=777816Capture.png

Do you know why ?
I have installed the plugin with this command

```
[root@srv sources]# ../kibana/bin/kibana plugin -i kbn_picture_values_vis  -u file:///data/ELK/sources/kbn_picture_values_vis-master.zip
Installing kbn_picture_values_vis
Attempting to transfer from file:///data/ELK/sources/kbn_picture_values_vis-master.zip
Transferring 57497 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

**Comment by JuanCarniglia** [comment]
Ok, give me a little more info.

You installed the plugin. You can see it on the Plugins List (In the
Visualization Selection Pane). You can select it, and what exactly is your
issue?

Thanks

2016-05-30 6:58 GMT-03:00 pittoch notifications@github.com:

> Hi,
> 
> When I wan to personalize the the json label, it's not possible. The label
> is not editing:
> 
> Do you know why ?
> I have installed the plugin with this command
> 
> [root@srv sources]# ../kibana/bin/kibana plugin -i kbn_picture_values_vis  -u file:///data/ELK/sources/kbn_picture_values_vis-master.zip
> Installing kbn_picture_values_vis
> Attempting to transfer from file:///data/ELK/sources/kbn_picture_values_vis-master.zip
> Transferring 57497 bytes....................
> Transfer complete
> Extracting plugin archive
> Extraction complete
> Optimizing and caching browser bundles...
> Plugin installation complete
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_picture_values_vis/issues/1, or mute
> the thread
> https://github.com/notifications/unsubscribe/AOi0O4tqJIKqHW2OqPiASIpzS7MOJhy8ks5qGrTggaJpZM4IpqJo
> .

## 

Juan Ignacio Carniglia

**Comment by pittoch** [comment]
Hi,

When I want to personalize the picture, the minimum, and the maximum value, I open the Options page, but I can't edit the json label section.
You can in this capture http://img15.hostingpics.net/pics/777816Capture.png that the label can't be editting
I use Kibana 4.5.
Thanks

**Comment by JuanCarniglia** [comment]
I see what you mean. Check if you have the latest version of the plugin
(specially the file "_kbn_picture_values_vis_params.html_".

It seems that either you have a previous version, or a broken one.

Also, tell me what browser (IE, Chrome) you are using, perhaps is an issue
with the browser.

Thanks!

2016-05-30 10:24 GMT-03:00 pittoch notifications@github.com:

> Hi,
> 
> When I want to personalize the picture, the minimum, and the maximum
> value, I open the Options page, but I can't edit the json label section.
> You can in this capture
> http://img15.hostingpics.net/pics/777816Capture.png that the label can't
> be editting.
> Thanks
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_picture_values_vis/issues/1#issuecomment-222492135,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0OxURCvEGno6IbrTG7QN9P7wagtaAks5qGuUagaJpZM4IpqJo
> .

## 

Juan Ignacio Carniglia

**Comment by pittoch** [comment]
Hello
I again download the current zip version from github:
https://github.com/JuanCarniglia/kbn_picture_values_vis/archive/master.zip

But the file is the same size as the first time.
I reinstalled everything with latest release of Kibana 4.5.1 and ElasticSearch : 2.3.3, but I have the same problem.

Regards

**Comment by JuanCarniglia** [comment]
What browser are you using (and which version)?

**Comment by pittoch** [comment]
Hi,

I use Chrome Version 38.0.2125.104 m
I have the same problem with Firefox 43.0.4 and InternetExplorer 11.0.9600.17801

Regards

**Comment by JuanCarniglia** [comment]
Please check it out now (grab the updated version). I am using ACE as the Json editor, so it should be more visible.
