### ISSUE TITLE
Can't display more than one in a Dashboard

### ISSUE THREAD

**Issue by SRLucia** [JuanCarniglia/kbn_picture_values_vis#2]
Hi!

I downloaded your plugin 'cause is really helpful for me to display status information. I configure it perfectly, but when I want to show more than one of these visualization in the same Dashboard, the only one visible is the one that was asses the last, the previous one becomes blank.

It does only support to use one by Dashboard?? I would really need to show a few of them.

I would appreciate your help!

Thank you!

**Comment by JuanCarniglia** [comment]
Look, I have both added more than one visualization, and also more than one
in one visualization:

[image: Imágenes integradas 1]

Maybe if you can give me more information (share your options information
with me).

If you want to add more than one value into the same visualization, then
you have to add the corresponding json information, on the options.

Thanks

2016-06-07 7:03 GMT-03:00 SRLucia notifications@github.com:

> Hi!
> 
> I downloaded your plugin 'cause is really helpful for me to display status
> information. I configure it perfectly, but when I want to show more than
> one of these visualization in the same Dashboard, the only one visible is
> the one that was asses the last, the previous one becomes blank.
> 
> It does only support to use one by Dashboard?? I would really need to show
> a few of them.
> 
> I would appreciate your help!
> 
> Thank you!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_picture_values_vis/issues/2, or mute
> the thread
> https://github.com/notifications/unsubscribe/AOi0O4xGbGTuEe0EMd4f1o8y9t7J0D7aks5qJUH2gaJpZM4IvwgW
> .

## 

Juan Ignacio Carniglia

**Comment by JuanCarniglia** [comment]
It was indeed a bug. Solved.

Thanks!
